### ISSUE TITLE
Option to select beta programs

### ISSUE THREAD

**Issue by amigthea** [r-pufky/steam#3]
How can i select a beta during server install?

**Comment by r-pufky** [comment]
Please let me know what server your trying to run, setuo, etc.

Happy to update container to deal with beta cases if they are not currently working, just need to know the use case.

**Comment by amigthea** [comment]
sure
it's the 7dtd server, prior testing your docker project i was running the -beta <beta name> parameter with appupdate in the steamcmd command line; I think an env variable should work? along the port, steamapp id etc you already implemented? 
thank you for your time either way


________________________________
Da: r-pufky <notifications@github.com>
Inviato: lunedì 29 giugno 2020 22:00
A: r-pufky/steam
Cc: Azertooth; Author
Oggetto: Re: [r-pufky/steam] Option to select beta programs (#3)

Please let me know what server your trying to run, setuo, etc.

Happy to update container to deal with beta cases if they are not currently working, just need to know the use case.

**Comment by r-pufky** [comment]
I've added the docker option, `STEAM_APP_EXTRAS`, you can add your additional options for app updates there, which should cover your `-beta` flags case. New images are pushed.

**Comment by amigthea** [comment]
amazing, thank for your work! 


________________________________
Da: r-pufky <notifications@github.com>
Inviato: giovedì 2 luglio 2020 05:53
A: r-pufky/steam
Cc: Azertooth; Author
Oggetto: Re: [r-pufky/steam] Option to select beta programs (#3)

I've added the docker option, STEAM_APP_EXTRAS, you can add your additional options for app updates there, which should cover your -beta flags case. New images are pushed.
